import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#07111F',
  },
  phone: {
    alignSelf: 'center',
    flex: 1,
    maxWidth: 430,
    width: '100%',
  },
  screen: {
    backgroundColor: 'transparent',
    flex: 1,
  },
  content: {
    paddingBottom: 116,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  headerRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  greeting: {
    color: '#C9D1E2',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 10,
  },
  heroQuestion: {
    color: '#FFFFFF',
    fontSize: 31,
    fontWeight: '900',
    letterSpacing: -0.2,
    lineHeight: 37,
  },
  profileStack: {
    alignItems: 'center',
    gap: 5,
  },
  profileName: {
    color: '#D9E2F2',
    fontSize: 11,
    fontWeight: '900',
  },
  headerAvatar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 27,
    borderWidth: 1,
    height: 68,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 68,
  },
  headerAvatarImage: {
    height: 76,
    width: 76,
  },
  identityPanel: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 14,
  },
  identityTopRow: {
    gap: 5,
  },
  identityLabel: {
    color: '#AEBBD0',
    fontSize: 11,
    fontWeight: '800',
  },
  identityValue: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: '900',
  },
  identityDivider: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    height: 1,
    marginVertical: 11,
  },
  identityGrid: {
    flexDirection: 'row',
    gap: 14,
  },
  identityColumn: {
    flex: 1,
  },
  identityFocus: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 5,
  },
  identityNext: {
    color: '#FFD166',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 5,
  },
  worldContent: {
    marginTop: 0,
  },
  todayShadow: {
    borderRadius: 24,
    marginTop: 6,
    shadowColor: '#FFB347',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 22,
    elevation: 10,
  },
  todayCard: {
    borderColor: 'rgba(255, 209, 102, 0.76)',
    borderRadius: 24,
    borderWidth: 1.4,
    height: 286,
    overflow: 'hidden',
  },
  todayArt: {
    bottom: 0,
    height: '100%',
    position: 'absolute',
    right: 0,
    width: '100%',
  },
  todayTextGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '56%',
  },
  todayCopy: {
    left: 24,
    position: 'absolute',
    top: 22,
    width: 222,
  },
  todayPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 235, 160, 0.96)',
    borderRadius: 999,
    justifyContent: 'center',
    marginBottom: 13,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  todayPillText: {
    color: '#30220A',
    fontSize: 11,
    fontWeight: '900',
  },
  todayTitle: {
    color: '#FFFFFF',
    fontSize: 27,
    fontWeight: '900',
    lineHeight: 30,
  },
  todayDescription: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
    marginTop: 10,
  },
  metaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 10,
  },
  metaText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  metaDot: {
    backgroundColor: '#FFFFFF',
    borderRadius: 3,
    height: 5,
    opacity: 0.62,
    width: 5,
  },
  continueButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 243, 188, 0.97)',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    width: 142,
  },
  continueText: {
    color: '#23180B',
    fontSize: 14,
    fontWeight: '900',
  },
  playButton: {
    alignItems: 'center',
    backgroundColor: '#FFD166',
    borderRadius: 12,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  lockedCard: {
    borderColor: 'rgba(148, 120, 255, 0.24)',
    borderRadius: 22,
    borderWidth: 1,
    height: 156,
    marginTop: 14,
    overflow: 'hidden',
  },
  lockedArt: {
    bottom: -2,
    height: 150,
    position: 'absolute',
    right: 6,
    width: 148,
  },
  lockedIllustrationFade: {
    opacity: 0.58,
  },
  lockedGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '82%',
  },
  lockedCopy: {
    left: 18,
    position: 'absolute',
    top: 18,
    width: 230,
  },
  lockedTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginBottom: 13,
  },
  lockedStatus: {
    color: '#E8ECF6',
    fontSize: 12,
    fontWeight: '900',
  },
  lockedTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 26,
  },
  lockedDescription: {
    color: '#C9D1E2',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
    marginTop: 8,
  },
  sectionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 24,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: '900',
  },
  seeAll: {
    color: '#AEBBD0',
    fontSize: 12,
    fontWeight: '900',
  },
  categoryRow: {
    gap: 14,
    paddingRight: 24,
  },
  categoryTile: {
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 24,
    borderWidth: 1,
    height: 152,
    overflow: 'hidden',
    padding: 16,
    width: 326,
  },
  categoryTileActive: {
    borderColor: 'rgba(255,255,255,0.62)',
  },
  categoryArt: {
    bottom: 0,
    height: 150,
    opacity: 0.82,
    position: 'absolute',
    right: 0,
    width: 152,
  },
  categoryFade: {
    bottom: 0,
    height: 92,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  categoryIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 17,
    height: 42,
    justifyContent: 'center',
    width: 42,
    zIndex: 2,
  },
  categoryText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
    marginTop: 38,
    zIndex: 2,
  },
  categoryTextActive: {
    color: '#FFFFFF',
  },
  homeEndSpacer: {
    height: 22,
  },
  detailContent: {
    paddingBottom: 116,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  detailTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  detailRoundButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.09)',
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 17,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  favoriteButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.09)',
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 17,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  detailHero: {
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 28,
    borderWidth: 1,
    height: 330,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
  },
  detailHeroImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  detailHeroGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '72%',
  },
  detailHeroCopy: {
    bottom: 24,
    left: 22,
    position: 'absolute',
    width: 260,
  },
  detailBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 235, 160, 0.96)',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 7,
    marginBottom: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  detailBadgeText: {
    color: '#101827',
    fontSize: 12,
    fontWeight: '900',
  },
  detailTitle: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 38,
  },
  detailMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginTop: 12,
  },
  detailSection: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 16,
    padding: 18,
  },
  detailSectionTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 12,
  },
  detailBodyText: {
    color: '#C9D1E2',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
    marginTop: 7,
  },
  actionGrid: {
    gap: 10,
    marginTop: 16,
  },
  actionButton: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 62,
    paddingHorizontal: 16,
  },
  actionButtonHighlighted: {
    borderColor: 'rgba(255, 209, 102, 0.62)',
  },
  actionButtonText: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
  },
  actionButtonTextHighlighted: {
    color: '#101827',
  },
  earnGrid: {
    gap: 10,
  },
  earnItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 17,
    flexDirection: 'row',
    gap: 12,
    padding: 13,
  },
  earnIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 209, 102, 0.14)',
    borderRadius: 14,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  earnLabel: {
    color: '#AEBBD0',
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
  },
  earnValue: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  recommendationRow: {
    gap: 12,
    paddingRight: 12,
  },
  recommendedCard: {
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 20,
    borderWidth: 1,
    height: 150,
    overflow: 'hidden',
    width: 150,
  },
  recommendedImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  recommendedFade: {
    bottom: 0,
    height: 90,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  recommendedTitle: {
    bottom: 13,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    left: 13,
    lineHeight: 18,
    position: 'absolute',
    right: 13,
  },
  bottomNav: {
    alignItems: 'center',
    backgroundColor: 'rgba(8, 15, 31, 0.96)',
    borderColor: 'rgba(148, 120, 255, 0.36)',
    borderRadius: 24,
    borderWidth: 1,
    bottom: 15,
    flexDirection: 'row',
    height: 66,
    justifyContent: 'space-around',
    left: 24,
    position: 'absolute',
    right: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.36,
    shadowRadius: 18,
    elevation: 10,
  },
  navItem: {
    alignItems: 'center',
    gap: 4,
    justifyContent: 'center',
    width: 60,
  },
  navLabel: {
    color: '#9AA6BC',
    fontSize: 10,
    fontWeight: '800',
  },
  navLabelActive: {
    color: '#FFD166',
  },
});
