import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from './index';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  phone: {
    alignSelf: 'center',
    flex: 1,
    maxWidth: 430,
    width: '100%',
  },
  screen: {
    backgroundColor: colors.background.transparent,
    flex: 1,
  },
  loadingState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.s24,
  },
  loadingText: {
    color: colors.text.primary,
    fontSize: typography.size.bodyLarge,
    fontWeight: typography.weight.black,
  },
  content: {
    paddingBottom: spacing.s116,
    paddingHorizontal: spacing.s24,
    paddingTop: spacing.s24,
  },
  headerRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.s12,
  },
  greeting: {
    color: colors.text.soft,
    fontSize: typography.size.action,
    fontWeight: typography.weight.bold,
    marginBottom: spacing.s10,
  },
  heroQuestion: {
    color: colors.text.primary,
    fontSize: typography.size.homeHero,
    fontWeight: typography.weight.black,
    letterSpacing: -0.2,
    lineHeight: 37,
  },
  profileStack: {
    alignItems: 'center',
    gap: spacing.sm,
  },
  profileName: {
    color: colors.text.pale,
    fontSize: typography.size.eyebrow,
    fontWeight: typography.weight.black,
  },
  headerAvatar: {
    alignItems: 'center',
    backgroundColor: colors.background.white07,
    borderColor: colors.border.white12,
    borderRadius: 27,
    borderWidth: 1,
    height: 68,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 68,
  },
  headerAvatarImage: {
    height: 76,
    width: 76,
  },
  identityPanel: {
    backgroundColor: colors.background.white06,
    borderColor: colors.border.white12,
    borderRadius: radius.button,
    borderWidth: 1,
    marginBottom: spacing.s14,
    padding: spacing.s14,
  },
  identityTopRow: {
    gap: spacing.sm,
  },
  identityLabel: {
    color: colors.text.muted,
    fontSize: typography.size.eyebrow,
    fontWeight: typography.weight.heavy,
  },
  identityValue: {
    color: colors.text.primary,
    fontSize: typography.size.section,
    fontWeight: typography.weight.black,
  },
  identityDivider: {
    backgroundColor: colors.background.white10,
    height: 1,
    marginVertical: spacing.s11,
  },
  identityGrid: {
    flexDirection: 'row',
    gap: spacing.s14,
  },
  identityColumn: {
    flex: 1,
  },
  identityFocus: {
    color: colors.text.primary,
    fontSize: typography.size.body,
    fontWeight: typography.weight.black,
    marginTop: spacing.sm,
  },
  identityNext: {
    color: colors.accent.gold,
    fontSize: typography.size.body,
    fontWeight: typography.weight.black,
    marginTop: spacing.sm,
  },
  worldContent: {
    marginTop: 0,
  },
  todayShadow: {
    borderRadius: radius.xl,
    marginTop: spacing.md,
    shadowColor: colors.accent.orange,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 22,
    elevation: 10,
  },
  todayCard: {
    borderColor: colors.border.goldHero,
    borderRadius: radius.xl,
    borderWidth: 1.4,
    height: 286,
    overflow: 'hidden',
  },
  todayArt: {
    bottom: 0,
    height: '100%',
    position: 'absolute',
    right: 0,
    width: '100%',
  },
  todayTextGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '56%',
  },
  todayCopy: {
    left: 24,
    position: 'absolute',
    top: 22,
    width: 222,
  },
  todayPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.accent.pill,
    borderRadius: radius.full,
    justifyContent: 'center',
    marginBottom: spacing.s13,
    paddingHorizontal: spacing.s14,
    paddingVertical: 8,
  },
  todayPillText: {
    color: colors.text.brownDeep,
    fontSize: typography.size.eyebrow,
    fontWeight: typography.weight.black,
  },
  todayTitle: {
    color: colors.text.primary,
    fontSize: typography.size.heroCard,
    fontWeight: typography.weight.black,
    lineHeight: 30,
  },
  todayDescription: {
    color: colors.text.primary,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.heavy,
    lineHeight: 16,
    marginTop: spacing.s10,
  },
  metaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.s10,
  },
  metaText: {
    color: colors.text.primary,
    fontSize: typography.size.bodySmall,
    fontWeight: typography.weight.heavy,
  },
  metaDot: {
    backgroundColor: colors.text.primary,
    borderRadius: radius.sm,
    height: 5,
    opacity: 0.62,
    width: 5,
  },
  continueButton: {
    alignItems: 'center',
    backgroundColor: colors.accent.continue,
    borderRadius: radius.pillSmall,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.xl,
    paddingHorizontal: spacing.s12,
    paddingVertical: 9,
    width: 142,
  },
  continueText: {
    color: colors.text.navyDeep,
    fontSize: typography.size.body,
    fontWeight: typography.weight.black,
  },
  playButton: {
    alignItems: 'center',
    backgroundColor: colors.accent.gold,
    borderRadius: radius.pillSmall,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  lockedCard: {
    borderColor: colors.border.violetSoft,
    borderRadius: radius.large,
    borderWidth: 1,
    height: 156,
    marginTop: spacing.s14,
    overflow: 'hidden',
  },
  lockedArt: {
    bottom: -2,
    height: 150,
    position: 'absolute',
    right: 6,
    width: 148,
  },
  lockedIllustrationFade: {
    opacity: 0.58,
  },
  lockedGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '82%',
  },
  lockedCopy: {
    left: 18,
    position: 'absolute',
    top: 18,
    width: 230,
  },
  lockedTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.lg,
    marginBottom: spacing.s13,
  },
  lockedStatus: {
    color: colors.text.bright,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.black,
  },
  lockedTitle: {
    color: colors.text.primary,
    fontSize: typography.size.titleSmall,
    fontWeight: typography.weight.black,
    lineHeight: 26,
  },
  lockedDescription: {
    color: colors.text.soft,
    fontSize: typography.size.body,
    fontWeight: typography.weight.bold,
    lineHeight: 19,
    marginTop: spacing.xl,
  },
  sectionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.s12,
    marginTop: spacing.s24,
  },
  sectionTitle: {
    color: colors.text.primary,
    fontSize: typography.size.section,
    fontWeight: typography.weight.black,
  },
  seeAll: {
    color: colors.text.muted,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.black,
  },
  categoryRow: {
    gap: spacing.s14,
    paddingRight: 24,
  },
  categoryTile: {
    borderColor: colors.background.white16,
    borderRadius: radius.xl,
    borderWidth: 1,
    height: 152,
    overflow: 'hidden',
    padding: spacing.s16,
    width: 326,
  },
  categoryTileActive: {
    borderColor: colors.border.white62,
  },
  categoryArt: {
    bottom: 0,
    height: 150,
    opacity: 0.82,
    position: 'absolute',
    right: 0,
    width: 152,
  },
  categoryFade: {
    bottom: 0,
    height: 92,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  categoryIcon: {
    alignItems: 'center',
    backgroundColor: colors.background.white16,
    borderRadius: radius.medium,
    height: 42,
    justifyContent: 'center',
    width: 42,
    zIndex: 2,
  },
  categoryText: {
    color: colors.text.primary,
    fontSize: typography.size.category,
    fontWeight: typography.weight.black,
    lineHeight: 32,
    marginTop: 38,
    zIndex: 2,
  },
  categoryTextActive: {
    color: colors.text.primary,
  },
  homeEndSpacer: {
    height: 22,
  },
  cloudHomeScroll: {
    flex: 1,
  },
  cloudHomeContent: {
    paddingBottom: spacing.s116,
  },
  cloudBedroomHero: {
    backgroundColor: colors.background.ink,
    height: 512,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: colors.shadow.black,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.38,
    shadowRadius: 30,
  },
  cloudBedroomImage: {
    height: '100%',
    left: 0,
    position: 'absolute',
    top: 0,
    width: '100%',
  },
  cloudBedroomFade: {
    bottom: 0,
    height: 136,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  heroStorybookTapTarget: {
    bottom: 34,
    height: 126,
    left: 26,
    position: 'absolute',
    width: 188,
    zIndex: 6,
  },
  heroStorybookTapGlow: {
    backgroundColor: colors.background.transparent,
    borderRadius: radius.large,
    flex: 1,
  },
  cloudHomeCards: {
    gap: spacing.s24,
    marginTop: -18,
    paddingHorizontal: spacing.s24,
    position: 'relative',
    zIndex: 3,
  },
  homeTodayCard: {
    borderColor: colors.border.white58,
    borderRadius: radius.poster,
    borderWidth: 1,
    height: 240,
    overflow: 'hidden',
    padding: spacing.s22,
    shadowColor: colors.shadow.gold,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.26,
    shadowRadius: 26,
  },
  homeTodayCopy: {
    position: 'relative',
    width: '58%',
    zIndex: 2,
  },
  homeStoryPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.accent.pill,
    borderRadius: radius.full,
    flexDirection: 'row',
    gap: spacing.lg,
    marginBottom: spacing.s16,
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.xl,
  },
  homeStoryPillText: {
    color: colors.text.brownMuted,
    fontSize: typography.size.eyebrow,
    fontWeight: typography.weight.black,
  },
  homeTodayTitle: {
    color: colors.background.ink,
    fontSize: typography.size.journeyTitle,
    fontWeight: typography.weight.black,
    lineHeight: 36,
  },
  homeTodaySubtitle: {
    color: colors.text.brownDeep,
    fontSize: typography.size.copy,
    fontWeight: typography.weight.bold,
    lineHeight: 24,
    marginTop: spacing.s12,
  },
  homeTodayMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.s18,
    marginTop: spacing.s24,
  },
  homeTodayMetaItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xl,
  },
  homeTodayMetaValue: {
    color: colors.text.brownDeep,
    fontSize: typography.size.body,
    fontWeight: typography.weight.black,
  },
  homeTodayMetaLabel: {
    color: colors.text.brownMuted,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.bold,
    marginTop: spacing.xxs,
  },
  homeNeedsWantsJars: {
    height: 108,
    position: 'absolute',
    right: 20,
    top: 46,
    width: 164,
  },
  startStoryButton: {
    alignItems: 'center',
    backgroundColor: colors.background.ink,
    borderRadius: radius.full,
    bottom: 24,
    flexDirection: 'row',
    gap: spacing.s10,
    height: 58,
    justifyContent: 'center',
    paddingHorizontal: spacing.s20,
    position: 'absolute',
    right: 22,
    shadowColor: colors.shadow.black,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
    width: 178,
  },
  startStoryText: {
    color: colors.accent.goldLight,
    fontSize: typography.size.action,
    fontWeight: typography.weight.black,
  },
  homeLockedCard: {
    alignItems: 'center',
    borderColor: colors.border.white12,
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    height: 108,
    marginBottom: spacing.s14,
    overflow: 'hidden',
    paddingLeft: spacing.s18,
    paddingRight: spacing.s18,
    shadowColor: colors.shadow.black,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
  },
  homeLockedIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.background.white09,
    borderRadius: radius.full,
    height: 58,
    justifyContent: 'center',
    marginRight: spacing.s16,
    width: 58,
  },
  homeLockedCopy: {
    flex: 1,
    paddingRight: spacing.s92,
  },
  homeLockedEyebrow: {
    color: colors.text.muted,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.black,
    letterSpacing: 0.6,
    marginBottom: spacing.xl,
  },
  homeLockedTitle: {
    color: colors.text.primary,
    fontSize: typography.size.section,
    fontWeight: typography.weight.black,
    lineHeight: 24,
  },
  homeLockedBody: {
    color: colors.text.soft,
    fontSize: typography.size.body,
    fontWeight: typography.weight.bold,
    lineHeight: 20,
    marginTop: spacing.sm,
  },
  homeLockedBook: {
    height: 74,
    opacity: 0.82,
    position: 'absolute',
    right: 42,
    width: 74,
  },
  homeLockedChevron: {
    position: 'absolute',
    right: 18,
  },
  cloudHome: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  morningGlow: {
    backgroundColor: colors.accent.sunlight,
    borderRadius: 180,
    height: 360,
    position: 'absolute',
    right: -110,
    top: -90,
    width: 360,
  },
  sunBeamOne: {
    backgroundColor: colors.accent.sunbeam,
    height: 560,
    position: 'absolute',
    right: 18,
    top: -80,
    transform: [{ rotate: '18deg' }],
    width: 72,
  },
  sunBeamTwo: {
    backgroundColor: colors.accent.sunbeamSoft,
    height: 520,
    position: 'absolute',
    right: 118,
    top: -40,
    transform: [{ rotate: '18deg' }],
    width: 46,
  },
  bedroomWall: {
    backgroundColor: colors.room.wall,
    borderBottomColor: colors.border.woodFloor,
    borderBottomWidth: 1,
    height: '72%',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  bedroomWindow: {
    backgroundColor: colors.room.windowFrame,
    borderColor: colors.border.woodSoft,
    borderRadius: radius.xxl,
    borderWidth: 8,
    height: 182,
    left: 28,
    overflow: 'hidden',
    position: 'absolute',
    top: 52,
    width: 178,
  },
  windowSky: {
    flex: 1,
  },
  windowSun: {
    backgroundColor: colors.accent.goldSoft,
    borderRadius: 26,
    height: 52,
    position: 'absolute',
    right: 28,
    top: 24,
    width: 52,
  },
  windowHillBack: {
    backgroundColor: colors.room.hillBack,
    borderRadius: 90,
    bottom: -42,
    height: 108,
    left: -38,
    position: 'absolute',
    width: 170,
  },
  windowHillFront: {
    backgroundColor: colors.room.hillFront,
    borderRadius: 100,
    bottom: -48,
    height: 122,
    position: 'absolute',
    right: -42,
    width: 178,
  },
  windowFrameVertical: {
    backgroundColor: colors.background.white86,
    bottom: 0,
    left: '49%',
    position: 'absolute',
    top: 0,
    width: 5,
  },
  windowFrameHorizontal: {
    backgroundColor: colors.background.white86,
    height: 5,
    left: 0,
    position: 'absolute',
    right: 0,
    top: '49%',
  },
  bookshelf: {
    backgroundColor: colors.room.bookshelf,
    borderRadius: radius.button,
    height: 116,
    position: 'absolute',
    right: 26,
    top: 70,
    width: 126,
  },
  bookSpine: {
    borderRadius: radius.lg,
    bottom: 24,
    position: 'absolute',
    width: 17,
  },
  bookSpineGold: {
    backgroundColor: colors.accent.goldBook,
    height: 58,
    left: 17,
  },
  bookSpineNavy: {
    backgroundColor: colors.room.navyObject,
    height: 72,
    left: 40,
  },
  bookSpineCream: {
    backgroundColor: colors.accent.cream,
    height: 50,
    left: 64,
  },
  bookSpineGreen: {
    backgroundColor: colors.room.hillFront,
    height: 64,
    left: 88,
  },
  shelfBoard: {
    backgroundColor: colors.room.wood,
    borderRadius: radius.lg,
    bottom: 18,
    height: 9,
    left: 12,
    position: 'absolute',
    right: 12,
  },
  backpackHook: {
    backgroundColor: colors.room.wood,
    borderRadius: radius.roundSmall,
    height: 14,
    position: 'absolute',
    right: 78,
    top: 232,
    width: 14,
  },
  backpack: {
    backgroundColor: colors.room.navyObject,
    borderColor: colors.background.white22,
    borderRadius: radius.xl,
    borderWidth: 1,
    height: 92,
    position: 'absolute',
    right: 48,
    top: 244,
    width: 72,
  },
  backpackPocket: {
    backgroundColor: colors.accent.gold16,
    borderColor: colors.border.goldSoft,
    borderRadius: radius.soft,
    borderWidth: 1,
    bottom: 13,
    height: 30,
    left: 12,
    position: 'absolute',
    right: 12,
  },
  cloudGreetingCard: {
    backgroundColor: colors.background.white86,
    borderColor: colors.border.white74,
    borderRadius: radius.xl,
    borderWidth: 1,
    left: 214,
    padding: spacing.s18,
    position: 'absolute',
    top: 292,
    width: 188,
    shadowColor: colors.shadow.warm,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    zIndex: 5,
  },
  cloudGreetingTail: {
    backgroundColor: colors.background.white86,
    borderBottomRightRadius: 6,
    height: 22,
    left: -8,
    position: 'absolute',
    top: 26,
    transform: [{ rotate: '42deg' }],
    width: 22,
  },
  cloudGreetingText: {
    color: colors.text.ink,
    fontSize: typography.size.titleSmall,
    fontWeight: typography.weight.black,
    lineHeight: 27,
  },
  cloudGreetingSubtext: {
    color: colors.text.ink,
    fontSize: typography.size.bodyLarge,
    fontWeight: typography.weight.heavy,
    lineHeight: 22,
    marginTop: spacing.s12,
  },
  deskCloudStage: {
    borderRadius: radius.poster,
    bottom: 176,
    height: 250,
    left: 142,
    overflow: 'hidden',
    position: 'absolute',
    width: 250,
    zIndex: 3,
  },
  deskCloudImage: {
    height: '100%',
    width: '100%',
  },
  cloudBlinkLayer: {
    height: 34,
    left: 118,
    position: 'absolute',
    top: 73,
    width: 82,
  },
  cloudEyeExpressionLayer: {
    height: 34,
    left: 118,
    position: 'absolute',
    top: 66,
    width: 82,
  },
  cloudExpressionBrowLeft: {
    backgroundColor: colors.face.brow,
    borderRadius: radius.md,
    height: 3,
    left: 7,
    position: 'absolute',
    top: 8,
  },
  cloudExpressionBrowRight: {
    backgroundColor: colors.face.brow,
    borderRadius: radius.md,
    height: 3,
    position: 'absolute',
    right: 12,
    top: 8,
  },
  cloudBlinkEyeLeft: {
    backgroundColor: colors.face.blink,
    borderRadius: radius.md,
    height: 4,
    left: 7,
    position: 'absolute',
    top: 14,
    width: 20,
  },
  cloudBlinkEyeRight: {
    backgroundColor: colors.face.blink,
    borderRadius: radius.md,
    height: 4,
    position: 'absolute',
    right: 12,
    top: 14,
    width: 20,
  },
  cloudSmileGlow: {
    backgroundColor: colors.accent.smile,
    borderRadius: 34,
    height: 68,
    left: 134,
    position: 'absolute',
    top: 82,
    width: 72,
  },
  cloudWaveHand: {
    height: 48,
    left: 70,
    position: 'absolute',
    top: 116,
    width: 42,
  },
  cloudWaveFingerOne: {
    backgroundColor: colors.accent.peach,
    borderRadius: radius.roundSmall,
    height: 24,
    left: 17,
    position: 'absolute',
    top: 1,
    transform: [{ rotate: '-16deg' }],
    width: 11,
  },
  cloudWaveFingerTwo: {
    backgroundColor: colors.accent.peach,
    borderRadius: radius.roundSmall,
    height: 22,
    left: 26,
    position: 'absolute',
    top: 5,
    transform: [{ rotate: '15deg' }],
    width: 10,
  },
  cloudWavePalm: {
    backgroundColor: colors.accent.peach,
    borderRadius: radius.soft,
    height: 27,
    left: 8,
    position: 'absolute',
    top: 17,
    width: 27,
  },
  woodenDesk: {
    bottom: 92,
    height: 178,
    left: 20,
    position: 'absolute',
    right: 20,
    zIndex: 4,
  },
  deskTop: {
    backgroundColor: colors.room.deskTop,
    borderRadius: radius.xxl,
    height: 86,
    shadowColor: colors.shadow.desk,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.28,
    shadowRadius: 20,
  },
  deskFront: {
    backgroundColor: colors.room.deskFront,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    height: 94,
    marginHorizontal: 20,
    marginTop: -8,
  },
  deskDrawer: {
    backgroundColor: colors.accent.gold09,
    borderColor: colors.border.drawer,
    borderRadius: radius.soft,
    borderWidth: 1,
    height: 44,
    left: 82,
    position: 'absolute',
    right: 82,
    top: 22,
  },
  deskKnob: {
    backgroundColor: colors.accent.gold,
    borderRadius: radius.lg,
    height: 10,
    left: '50%',
    marginLeft: -5,
    position: 'absolute',
    top: 39,
    width: 10,
  },
  storybookPressable: {
    bottom: 26,
    left: 30,
    position: 'absolute',
    zIndex: 3,
  },
  storybookAnimatedSurface: {
    transform: [{ rotate: '-8deg' }],
  },
  storybookCover: {
    borderColor: colors.border.white38,
    borderRadius: radius.button,
    borderWidth: 1,
    height: 122,
    overflow: 'hidden',
    padding: spacing.s14,
    shadowColor: colors.shadow.desk,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    width: 138,
  },
  storybookGlow: {
    backgroundColor: colors.background.white22,
    borderRadius: 48,
    height: 96,
    position: 'absolute',
    right: -28,
    top: -24,
    width: 96,
  },
  storybookEyebrow: {
    color: colors.text.brown,
    fontSize: typography.size.eyebrow,
    fontWeight: typography.weight.black,
  },
  storybookTitle: {
    color: colors.text.primary,
    fontSize: typography.size.titleSmall,
    fontWeight: typography.weight.black,
    lineHeight: 24,
    marginTop: spacing.xl,
  },
  storybookLine: {
    backgroundColor: colors.border.white58,
    borderRadius: radius.xs,
    height: 3,
    marginTop: spacing.s11,
    width: 68,
  },
  storybookHint: {
    color: colors.text.cream,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.black,
    marginTop: spacing.xl,
  },
  deskLamp: {
    position: 'absolute',
    right: 34,
    top: -54,
  },
  lampShade: {
    backgroundColor: colors.accent.goldLight,
    borderRadius: radius.large,
    height: 42,
    shadowColor: colors.accent.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 22,
    width: 76,
  },
  lampStem: {
    backgroundColor: colors.room.lampDark,
    height: 48,
    marginLeft: 34,
    width: 8,
  },
  lampBase: {
    backgroundColor: colors.room.lampDark,
    borderRadius: radius.button,
    height: 18,
    marginLeft: 18,
    width: 44,
  },
  bedroomFloor: {
    backgroundColor: colors.room.floor,
    bottom: 0,
    height: '30%',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  detailContent: {
    paddingBottom: spacing.s116,
    paddingHorizontal: spacing.s24,
    paddingTop: spacing.s20,
  },
  detailTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.s14,
  },
  detailRoundButton: {
    alignItems: 'center',
    backgroundColor: colors.background.white09,
    borderColor: colors.border.white14,
    borderRadius: radius.medium,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  favoriteButton: {
    alignItems: 'center',
    backgroundColor: colors.background.white09,
    borderColor: colors.border.white14,
    borderRadius: radius.medium,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  detailHero: {
    borderColor: colors.border.white14,
    borderRadius: radius.xxl,
    borderWidth: 1,
    height: 330,
    overflow: 'hidden',
    shadowColor: colors.shadow.black,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
  },
  detailHeroImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  detailHeroGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '72%',
  },
  detailHeroCopy: {
    bottom: 24,
    left: 22,
    position: 'absolute',
    width: 260,
  },
  detailBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.accent.pill,
    borderRadius: radius.full,
    flexDirection: 'row',
    gap: spacing.lg,
    marginBottom: spacing.s14,
    paddingHorizontal: spacing.s12,
    paddingVertical: 8,
  },
  detailBadgeText: {
    color: colors.background.ink,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.black,
  },
  detailTitle: {
    color: colors.text.primary,
    fontSize: typography.size.detailTitle,
    fontWeight: typography.weight.black,
    lineHeight: 38,
  },
  detailMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.lg,
    marginTop: spacing.s12,
  },
  detailSection: {
    backgroundColor: colors.background.white06,
    borderColor: colors.border.white12,
    borderRadius: radius.large,
    borderWidth: 1,
    marginTop: spacing.s16,
    padding: spacing.s18,
  },
  detailSectionTitle: {
    color: colors.text.primary,
    fontSize: typography.size.card,
    fontWeight: typography.weight.black,
    marginBottom: spacing.s12,
  },
  detailBodyText: {
    color: colors.text.soft,
    fontSize: typography.size.bodyLarge,
    fontWeight: typography.weight.bold,
    lineHeight: 22,
    marginTop: spacing.lg,
  },
  actionGrid: {
    gap: spacing.s10,
    marginTop: spacing.s16,
  },
  actionButton: {
    alignItems: 'center',
    borderColor: colors.border.white12,
    borderRadius: radius.button,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.s12,
    minHeight: 62,
    paddingHorizontal: spacing.s16,
  },
  actionButtonHighlighted: {
    borderColor: colors.border.goldStrong,
  },
  actionButtonText: {
    color: colors.text.primary,
    flex: 1,
    fontSize: typography.size.copy,
    fontWeight: typography.weight.black,
  },
  actionButtonTextHighlighted: {
    color: colors.background.ink,
  },
  earnGrid: {
    gap: spacing.s10,
  },
  earnItem: {
    alignItems: 'center',
    backgroundColor: colors.background.white07,
    borderRadius: radius.medium,
    flexDirection: 'row',
    gap: spacing.s12,
    padding: spacing.s13,
  },
  earnIcon: {
    alignItems: 'center',
    backgroundColor: colors.accent.gold14,
    borderRadius: radius.soft,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  earnLabel: {
    color: colors.text.muted,
    flex: 1,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.heavy,
  },
  earnValue: {
    color: colors.text.primary,
    flex: 1,
    fontSize: typography.size.bodySmall,
    fontWeight: typography.weight.black,
    textAlign: 'right',
  },
  recommendationRow: {
    gap: spacing.s12,
    paddingRight: 12,
  },
  recommendedCard: {
    borderColor: colors.border.white14,
    borderRadius: radius.card,
    borderWidth: 1,
    height: 150,
    overflow: 'hidden',
    width: 150,
  },
  recommendedImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  recommendedFade: {
    bottom: 0,
    height: 90,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  recommendedTitle: {
    bottom: 13,
    color: colors.text.primary,
    fontSize: typography.size.bodyLarge,
    fontWeight: typography.weight.black,
    left: 13,
    lineHeight: 18,
    position: 'absolute',
    right: 13,
  },
  journeyContent: {
    paddingBottom: spacing.s38,
    paddingHorizontal: spacing.s24,
    paddingTop: spacing.s20,
  },
  journeyStepPill: {
    alignItems: 'center',
    backgroundColor: colors.background.white09,
    borderColor: colors.border.white14,
    borderRadius: radius.full,
    borderWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.s14,
    paddingVertical: 9,
  },
  journeyStepText: {
    color: colors.text.pale,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.black,
  },
  journeyHero: {
    borderColor: colors.border.white14,
    borderRadius: radius.xxl,
    borderWidth: 1,
    height: 310,
    overflow: 'hidden',
    shadowColor: colors.shadow.black,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
  },
  journeyHeroImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  journeyHeroGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '78%',
  },
  journeyHeroCopy: {
    bottom: 24,
    left: 22,
    position: 'absolute',
    width: 270,
  },
  journeyTitle: {
    color: colors.text.primary,
    fontSize: typography.size.journeyTitle,
    fontWeight: typography.weight.black,
    lineHeight: 36,
  },
  journeyDescription: {
    color: colors.text.light,
    fontSize: typography.size.body,
    fontWeight: typography.weight.heavy,
    lineHeight: 20,
    marginTop: spacing.s10,
  },
  journeyPanel: {
    backgroundColor: colors.background.white06,
    borderColor: colors.border.white12,
    borderRadius: radius.large,
    borderWidth: 1,
    marginTop: spacing.s16,
    padding: spacing.s18,
  },
  journeyPanelTitle: {
    color: colors.text.primary,
    fontSize: typography.size.card,
    fontWeight: typography.weight.black,
    marginBottom: spacing.s12,
  },
  journeyBodyText: {
    color: colors.text.soft,
    fontSize: typography.size.bodyLarge,
    fontWeight: typography.weight.bold,
    lineHeight: 23,
  },
  journeyListItem: {
    alignItems: 'flex-start',
    backgroundColor: colors.background.white07,
    borderRadius: radius.medium,
    flexDirection: 'row',
    gap: spacing.s12,
    marginTop: spacing.s10,
    padding: spacing.s13,
  },
  journeyListIcon: {
    alignItems: 'center',
    backgroundColor: colors.accent.gold14,
    borderRadius: radius.soft,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  journeyListCopy: {
    flex: 1,
  },
  journeyListTitle: {
    color: colors.text.primary,
    fontSize: typography.size.body,
    fontWeight: typography.weight.black,
  },
  journeyListBody: {
    color: colors.text.soft,
    fontSize: typography.size.bodySmall,
    fontWeight: typography.weight.bold,
    lineHeight: 19,
    marginTop: spacing.xs,
  },
  cloudBubble: {
    backgroundColor: colors.accent.gold12,
    borderColor: colors.accent.gold28,
    borderRadius: radius.card,
    borderWidth: 1,
    padding: spacing.s16,
  },
  cloudBubbleText: {
    color: colors.text.primary,
    fontSize: typography.size.copy,
    fontWeight: typography.weight.heavy,
    lineHeight: 23,
  },
  journeyPrimaryButton: {
    alignItems: 'center',
    borderRadius: radius.button,
    flexDirection: 'row',
    gap: spacing.s10,
    justifyContent: 'center',
    marginTop: spacing.s18,
    minHeight: 58,
    paddingHorizontal: spacing.s18,
  },
  journeyPrimaryText: {
    color: colors.background.ink,
    fontSize: typography.size.action,
    fontWeight: typography.weight.black,
  },
  questionContent: {
    paddingBottom: spacing.s38,
    paddingHorizontal: spacing.s24,
    paddingTop: spacing.s20,
  },
  questionHero: {
    borderColor: colors.border.white14,
    borderRadius: radius.poster,
    borderWidth: 1,
    height: 350,
    overflow: 'hidden',
    shadowColor: colors.accent.orange,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.24,
    shadowRadius: 24,
  },
  questionHeroImage: {
    bottom: 0,
    height: '100%',
    position: 'absolute',
    right: 0,
    width: '100%',
  },
  questionHeroFade: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '82%',
  },
  questionHeroCopy: {
    bottom: 26,
    left: 22,
    position: 'absolute',
    width: 276,
  },
  questionCloudLine: {
    color: colors.text.primary,
    fontSize: typography.size.prompt,
    fontWeight: typography.weight.black,
    lineHeight: 35,
  },
  questionPanel: {
    backgroundColor: colors.background.white06,
    borderColor: colors.border.white12,
    borderRadius: radius.xl,
    borderWidth: 1,
    marginTop: spacing.s16,
    padding: spacing.s18,
  },
  questionTitle: {
    color: colors.text.primary,
    fontSize: typography.size.question,
    fontWeight: typography.weight.black,
    lineHeight: 31,
  },
  answerStack: {
    gap: spacing.s12,
    marginTop: spacing.s18,
  },
  answerCard: {
    alignItems: 'center',
    backgroundColor: colors.background.white07,
    borderColor: colors.border.white12,
    borderRadius: radius.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.s13,
    minHeight: 76,
    paddingHorizontal: spacing.s16,
  },
  answerCardSelected: {
    backgroundColor: colors.accent.gold13,
    borderColor: colors.border.goldMedium,
  },
  answerIcon: {
    fontSize: typography.size.category,
  },
  answerText: {
    color: colors.text.primary,
    flex: 1,
    fontSize: typography.size.action,
    fontWeight: typography.weight.black,
    lineHeight: 22,
  },
  questionResponsePanel: {
    marginTop: spacing.s16,
  },
  storyScreen: {
    flex: 1,
  },
  storyPage: {
    flex: 1,
    overflow: 'hidden',
  },
  storyIllustration: {
    height: '72%',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  storyImageFade: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  storyTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 24,
    position: 'absolute',
    right: 24,
    top: 20,
    zIndex: 3,
  },
  storyCopyPanel: {
    bottom: 24,
    left: 24,
    position: 'absolute',
    right: 24,
    zIndex: 2,
  },
  storyTitle: {
    color: colors.text.primary,
    fontSize: typography.size.detailTitle,
    fontWeight: typography.weight.black,
    lineHeight: 38,
  },
  storyParagraphStack: {
    gap: spacing.xl,
    marginTop: spacing.s13,
  },
  storyParagraph: {
    color: colors.text.light,
    fontSize: typography.size.copy,
    fontWeight: typography.weight.heavy,
    lineHeight: 23,
  },
  storyContinueButton: {
    alignItems: 'center',
    borderRadius: radius.button,
    flexDirection: 'row',
    gap: spacing.s10,
    justifyContent: 'center',
    marginTop: spacing.s20,
    minHeight: 58,
    paddingHorizontal: spacing.s18,
  },
  storyContinueText: {
    color: colors.background.ink,
    fontSize: typography.size.action,
    fontWeight: typography.weight.black,
  },
  storyChoiceGrid: {
    gap: spacing.s12,
    marginTop: spacing.s18,
  },
  storyChoiceCard: {
    borderRadius: radius.large,
    height: 138,
    overflow: 'hidden',
    shadowColor: colors.shadow.black,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
  },
  storyChoiceGradient: {
    borderColor: colors.background.white16,
    borderRadius: radius.large,
    borderWidth: 1,
    flex: 1,
    overflow: 'hidden',
  },
  storyChoiceImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '56%',
  },
  storyChoiceFade: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  storyChoiceCopy: {
    bottom: 16,
    left: 16,
    position: 'absolute',
    right: 104,
  },
  storyChoiceTitle: {
    color: colors.text.primary,
    fontSize: typography.size.card,
    fontWeight: typography.weight.black,
    lineHeight: 23,
  },
  storyChoiceBody: {
    color: colors.text.story,
    fontSize: typography.size.bodySmall,
    fontWeight: typography.weight.heavy,
    lineHeight: 18,
    marginTop: spacing.lg,
  },
  congratsHero: {
    borderColor: colors.border.congrats,
    borderRadius: radius.poster,
    borderWidth: 1,
    height: 410,
    marginTop: spacing.xl,
    overflow: 'hidden',
    shadowColor: colors.accent.orange,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.26,
    shadowRadius: 26,
  },
  congratsHeroImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  congratsFade: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '84%',
  },
  congratsCopy: {
    bottom: 28,
    left: 24,
    position: 'absolute',
    right: 24,
  },
  congratsIcon: {
    alignItems: 'center',
    backgroundColor: colors.accent.gold,
    borderRadius: 21,
    height: 48,
    justifyContent: 'center',
    marginBottom: spacing.s16,
    width: 48,
  },
  congratsTitle: {
    color: colors.text.primary,
    fontSize: typography.size.congrats,
    fontWeight: typography.weight.black,
    lineHeight: 40,
  },
  congratsBody: {
    color: colors.text.light,
    fontSize: typography.size.copy,
    fontWeight: typography.weight.heavy,
    lineHeight: 23,
    marginTop: spacing.s10,
  },
  bottomNav: {
    alignItems: 'center',
    backgroundColor: colors.background.nav,
    borderColor: colors.border.violetMedium,
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    height: 66,
    justifyContent: 'space-around',
    marginBottom: spacing.s15,
    marginHorizontal: spacing.s24,
    shadowColor: colors.shadow.black,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.36,
    shadowRadius: 18,
    elevation: 10,
  },
  navItem: {
    alignItems: 'center',
    gap: spacing.xs,
    justifyContent: 'center',
    width: 60,
  },
  navLabel: {
    color: colors.text.navMuted,
    fontSize: typography.size.nav,
    fontWeight: typography.weight.heavy,
  },
  navLabelActive: {
    color: colors.accent.gold,
  },

  libraryIntro: {
    color: colors.text.muted,
    fontSize: typography.size.body,
    marginBottom: spacing.s24,
  },
  libraryCategoryBlock: {
    marginBottom: spacing.s24,
  },
  libraryCategoryTitle: {
    color: colors.text.primary,
    fontSize: typography.size.card,
    fontWeight: typography.weight.heavy,
    marginBottom: spacing.s12,
  },
  wisdomListItem: {
    alignItems: 'center',
    backgroundColor: colors.background.white06,
    borderColor: colors.border.white12,
    borderRadius: radius.large,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.s12,
    marginBottom: spacing.s12,
    padding: spacing.s12,
  },
  wisdomListThumb: {
    borderRadius: radius.medium,
    height: 56,
    width: 56,
  },
  wisdomListCopy: {
    flex: 1,
    gap: spacing.xxs,
  },
  wisdomListTitle: {
    color: colors.text.primary,
    fontSize: typography.size.body,
    fontWeight: typography.weight.heavy,
  },
  wisdomListSubtitle: {
    color: colors.text.muted,
    fontSize: typography.size.bodySmall,
  },
  wisdomListStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    marginTop: spacing.xxs,
  },
  wisdomListStatusText: {
    color: colors.text.navMuted,
    fontSize: typography.size.caption,
    fontWeight: typography.weight.bold,
  },

  journeyProgressBlock: {
    marginTop: spacing.s12,
  },
  journeyProgressRow: {
    marginBottom: spacing.s18,
  },
  journeyProgressLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  journeyProgressTitle: {
    color: colors.text.primary,
    fontSize: typography.size.body,
    fontWeight: typography.weight.heavy,
  },
  journeyProgressCount: {
    color: colors.text.muted,
    fontSize: typography.size.bodySmall,
  },
  journeyProgressTrack: {
    backgroundColor: colors.background.white09,
    borderRadius: radius.full,
    height: 8,
    overflow: 'hidden',
  },
  journeyProgressFill: {
    backgroundColor: colors.accent.gold,
    borderRadius: radius.full,
    height: 8,
  },

  profileIdentityCard: {
    alignItems: 'center',
    backgroundColor: colors.background.white06,
    borderColor: colors.border.white12,
    borderRadius: radius.xl,
    borderWidth: 1,
    marginBottom: spacing.s24,
    padding: spacing.s24,
  },
  profileIdentityIcon: {
    marginBottom: spacing.s12,
  },
  profileIdentityLabel: {
    color: colors.text.muted,
    fontSize: typography.size.bodySmall,
    marginBottom: spacing.xs,
  },
  profileIdentityValue: {
    color: colors.text.primary,
    fontSize: typography.size.titleSmall,
    fontWeight: typography.weight.black,
  },
  profileStatRow: {
    flexDirection: 'row',
    gap: spacing.s12,
  },
  profileStatCard: {
    alignItems: 'center',
    backgroundColor: colors.background.white06,
    borderColor: colors.border.white12,
    borderRadius: radius.large,
    borderWidth: 1,
    flex: 1,
    padding: spacing.s18,
  },
  profileStatValue: {
    color: colors.accent.gold,
    fontSize: typography.size.detailTitle,
    fontWeight: typography.weight.black,
  },
  profileStatLabel: {
    color: colors.text.muted,
    fontSize: typography.size.caption,
    marginTop: spacing.xs,
    textAlign: 'center',
  },

  cloudComingSoonWrap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.s24,
  },
  cloudComingSoonAvatar: {
    height: 140,
    marginBottom: spacing.s24,
    width: 140,
  },
  cloudComingSoonTitle: {
    color: colors.text.primary,
    fontSize: typography.size.titleSmall,
    fontWeight: typography.weight.black,
    marginBottom: spacing.s12,
    textAlign: 'center',
  },
  cloudComingSoonBody: {
    color: colors.text.muted,
    fontSize: typography.size.body,
    lineHeight: typography.size.body * 1.5,
    textAlign: 'center',
  },
});



