import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#07111F',
  },
  phone: {
    alignSelf: 'center',
    flex: 1,
    maxWidth: 430,
    width: '100%',
  },
  screen: {
    backgroundColor: 'transparent',
    flex: 1,
  },
  content: {
    paddingBottom: 116,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  headerRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  greeting: {
    color: '#C9D1E2',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 10,
  },
  heroQuestion: {
    color: '#FFFFFF',
    fontSize: 31,
    fontWeight: '900',
    letterSpacing: -0.2,
    lineHeight: 37,
  },
  profileStack: {
    alignItems: 'center',
    gap: 5,
  },
  profileName: {
    color: '#D9E2F2',
    fontSize: 11,
    fontWeight: '900',
  },
  headerAvatar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 27,
    borderWidth: 1,
    height: 68,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 68,
  },
  headerAvatarImage: {
    height: 76,
    width: 76,
  },
  identityPanel: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 14,
  },
  identityTopRow: {
    gap: 5,
  },
  identityLabel: {
    color: '#AEBBD0',
    fontSize: 11,
    fontWeight: '800',
  },
  identityValue: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: '900',
  },
  identityDivider: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    height: 1,
    marginVertical: 11,
  },
  identityGrid: {
    flexDirection: 'row',
    gap: 14,
  },
  identityColumn: {
    flex: 1,
  },
  identityFocus: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 5,
  },
  identityNext: {
    color: '#FFD166',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 5,
  },
  worldContent: {
    marginTop: 0,
  },
  todayShadow: {
    borderRadius: 24,
    marginTop: 6,
    shadowColor: '#FFB347',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 22,
    elevation: 10,
  },
  todayCard: {
    borderColor: 'rgba(255, 209, 102, 0.76)',
    borderRadius: 24,
    borderWidth: 1.4,
    height: 286,
    overflow: 'hidden',
  },
  todayArt: {
    bottom: 0,
    height: '100%',
    position: 'absolute',
    right: 0,
    width: '100%',
  },
  todayTextGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '56%',
  },
  todayCopy: {
    left: 24,
    position: 'absolute',
    top: 22,
    width: 222,
  },
  todayPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 235, 160, 0.96)',
    borderRadius: 999,
    justifyContent: 'center',
    marginBottom: 13,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  todayPillText: {
    color: '#30220A',
    fontSize: 11,
    fontWeight: '900',
  },
  todayTitle: {
    color: '#FFFFFF',
    fontSize: 27,
    fontWeight: '900',
    lineHeight: 30,
  },
  todayDescription: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
    marginTop: 10,
  },
  metaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 10,
  },
  metaText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  metaDot: {
    backgroundColor: '#FFFFFF',
    borderRadius: 3,
    height: 5,
    opacity: 0.62,
    width: 5,
  },
  continueButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 243, 188, 0.97)',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    width: 142,
  },
  continueText: {
    color: '#23180B',
    fontSize: 14,
    fontWeight: '900',
  },
  playButton: {
    alignItems: 'center',
    backgroundColor: '#FFD166',
    borderRadius: 12,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  lockedCard: {
    borderColor: 'rgba(148, 120, 255, 0.24)',
    borderRadius: 22,
    borderWidth: 1,
    height: 156,
    marginTop: 14,
    overflow: 'hidden',
  },
  lockedArt: {
    bottom: -2,
    height: 150,
    position: 'absolute',
    right: 6,
    width: 148,
  },
  lockedIllustrationFade: {
    opacity: 0.58,
  },
  lockedGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '82%',
  },
  lockedCopy: {
    left: 18,
    position: 'absolute',
    top: 18,
    width: 230,
  },
  lockedTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginBottom: 13,
  },
  lockedStatus: {
    color: '#E8ECF6',
    fontSize: 12,
    fontWeight: '900',
  },
  lockedTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 26,
  },
  lockedDescription: {
    color: '#C9D1E2',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
    marginTop: 8,
  },
  sectionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 24,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: '900',
  },
  seeAll: {
    color: '#AEBBD0',
    fontSize: 12,
    fontWeight: '900',
  },
  categoryRow: {
    gap: 14,
    paddingRight: 24,
  },
  categoryTile: {
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 24,
    borderWidth: 1,
    height: 152,
    overflow: 'hidden',
    padding: 16,
    width: 326,
  },
  categoryTileActive: {
    borderColor: 'rgba(255,255,255,0.62)',
  },
  categoryArt: {
    bottom: 0,
    height: 150,
    opacity: 0.82,
    position: 'absolute',
    right: 0,
    width: 152,
  },
  categoryFade: {
    bottom: 0,
    height: 92,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  categoryIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 17,
    height: 42,
    justifyContent: 'center',
    width: 42,
    zIndex: 2,
  },
  categoryText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
    marginTop: 38,
    zIndex: 2,
  },
  categoryTextActive: {
    color: '#FFFFFF',
  },
  homeEndSpacer: {
    height: 22,
  },
  cloudHome: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  morningGlow: {
    backgroundColor: 'rgba(255, 235, 177, 0.55)',
    borderRadius: 180,
    height: 360,
    position: 'absolute',
    right: -110,
    top: -90,
    width: 360,
  },
  sunBeamOne: {
    backgroundColor: 'rgba(255, 242, 196, 0.22)',
    height: 560,
    position: 'absolute',
    right: 18,
    top: -80,
    transform: [{ rotate: '18deg' }],
    width: 72,
  },
  sunBeamTwo: {
    backgroundColor: 'rgba(255, 242, 196, 0.14)',
    height: 520,
    position: 'absolute',
    right: 118,
    top: -40,
    transform: [{ rotate: '18deg' }],
    width: 46,
  },
  bedroomWall: {
    backgroundColor: '#F8DCA9',
    borderBottomColor: 'rgba(91, 55, 35, 0.24)',
    borderBottomWidth: 1,
    height: '72%',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  bedroomWindow: {
    backgroundColor: '#FDF5DE',
    borderColor: 'rgba(84, 55, 38, 0.2)',
    borderRadius: 28,
    borderWidth: 8,
    height: 182,
    left: 28,
    overflow: 'hidden',
    position: 'absolute',
    top: 52,
    width: 178,
  },
  windowSky: {
    flex: 1,
  },
  windowSun: {
    backgroundColor: '#FFE082',
    borderRadius: 26,
    height: 52,
    position: 'absolute',
    right: 28,
    top: 24,
    width: 52,
  },
  windowHillBack: {
    backgroundColor: '#8AC889',
    borderRadius: 90,
    bottom: -42,
    height: 108,
    left: -38,
    position: 'absolute',
    width: 170,
  },
  windowHillFront: {
    backgroundColor: '#5EA46C',
    borderRadius: 100,
    bottom: -48,
    height: 122,
    position: 'absolute',
    right: -42,
    width: 178,
  },
  windowFrameVertical: {
    backgroundColor: 'rgba(255,255,255,0.86)',
    bottom: 0,
    left: '49%',
    position: 'absolute',
    top: 0,
    width: 5,
  },
  windowFrameHorizontal: {
    backgroundColor: 'rgba(255,255,255,0.86)',
    height: 5,
    left: 0,
    position: 'absolute',
    right: 0,
    top: '49%',
  },
  bookshelf: {
    backgroundColor: 'rgba(117, 73, 43, 0.18)',
    borderRadius: 18,
    height: 116,
    position: 'absolute',
    right: 26,
    top: 70,
    width: 126,
  },
  bookSpine: {
    borderRadius: 5,
    bottom: 24,
    position: 'absolute',
    width: 17,
  },
  bookSpineGold: {
    backgroundColor: '#D98A2B',
    height: 58,
    left: 17,
  },
  bookSpineNavy: {
    backgroundColor: '#1E3A6A',
    height: 72,
    left: 40,
  },
  bookSpineCream: {
    backgroundColor: '#FFF4D5',
    height: 50,
    left: 64,
  },
  bookSpineGreen: {
    backgroundColor: '#5EA46C',
    height: 64,
    left: 88,
  },
  shelfBoard: {
    backgroundColor: '#7A4A2D',
    borderRadius: 5,
    bottom: 18,
    height: 9,
    left: 12,
    position: 'absolute',
    right: 12,
  },
  backpackHook: {
    backgroundColor: '#7A4A2D',
    borderRadius: 7,
    height: 14,
    position: 'absolute',
    right: 78,
    top: 232,
    width: 14,
  },
  backpack: {
    backgroundColor: '#1E3A6A',
    borderColor: 'rgba(255,255,255,0.22)',
    borderRadius: 24,
    borderWidth: 1,
    height: 92,
    position: 'absolute',
    right: 48,
    top: 244,
    width: 72,
  },
  backpackPocket: {
    backgroundColor: 'rgba(255, 209, 102, 0.16)',
    borderColor: 'rgba(255, 209, 102, 0.32)',
    borderRadius: 14,
    borderWidth: 1,
    bottom: 13,
    height: 30,
    left: 12,
    position: 'absolute',
    right: 12,
  },
  cloudGreetingCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderColor: 'rgba(255,255,255,0.74)',
    borderRadius: 24,
    borderWidth: 1,
    left: 24,
    padding: 18,
    position: 'absolute',
    top: 250,
    width: 250,
    shadowColor: '#8B5E34',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 22,
    zIndex: 5,
  },
  cloudGreetingTail: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderBottomRightRadius: 6,
    height: 24,
    position: 'absolute',
    right: 35,
    top: 70,
    transform: [{ rotate: '42deg' }],
    width: 24,
  },
  cloudGreetingText: {
    color: '#1B283A',
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 25,
  },
  cloudGreetingSubtext: {
    color: '#6A4A33',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
    marginTop: 8,
  },
  deskCloudStage: {
    borderRadius: 30,
    bottom: 176,
    height: 250,
    left: 142,
    overflow: 'hidden',
    position: 'absolute',
    width: 250,
    zIndex: 3,
  },
  deskCloudImage: {
    height: '100%',
    width: '100%',
  },
  cloudBlinkLayer: {
    height: 34,
    left: 118,
    position: 'absolute',
    top: 73,
    width: 82,
  },
  cloudEyeExpressionLayer: {
    height: 34,
    left: 118,
    position: 'absolute',
    top: 66,
    width: 82,
  },
  cloudExpressionBrowLeft: {
    backgroundColor: 'rgba(28, 20, 16, 0.5)',
    borderRadius: 4,
    height: 3,
    left: 7,
    position: 'absolute',
    top: 8,
  },
  cloudExpressionBrowRight: {
    backgroundColor: 'rgba(28, 20, 16, 0.5)',
    borderRadius: 4,
    height: 3,
    position: 'absolute',
    right: 12,
    top: 8,
  },
  cloudBlinkEyeLeft: {
    backgroundColor: 'rgba(20, 18, 15, 0.72)',
    borderRadius: 4,
    height: 4,
    left: 7,
    position: 'absolute',
    top: 14,
    width: 20,
  },
  cloudBlinkEyeRight: {
    backgroundColor: 'rgba(20, 18, 15, 0.72)',
    borderRadius: 4,
    height: 4,
    position: 'absolute',
    right: 12,
    top: 14,
    width: 20,
  },
  cloudSmileGlow: {
    backgroundColor: 'rgba(255, 214, 160, 0.24)',
    borderRadius: 34,
    height: 68,
    left: 134,
    position: 'absolute',
    top: 82,
    width: 72,
  },
  cloudWaveHand: {
    height: 48,
    left: 70,
    position: 'absolute',
    top: 116,
    width: 42,
  },
  cloudWaveFingerOne: {
    backgroundColor: '#F5B67B',
    borderRadius: 7,
    height: 24,
    left: 17,
    position: 'absolute',
    top: 1,
    transform: [{ rotate: '-16deg' }],
    width: 11,
  },
  cloudWaveFingerTwo: {
    backgroundColor: '#F5B67B',
    borderRadius: 7,
    height: 22,
    left: 26,
    position: 'absolute',
    top: 5,
    transform: [{ rotate: '15deg' }],
    width: 10,
  },
  cloudWavePalm: {
    backgroundColor: '#F5B67B',
    borderRadius: 14,
    height: 27,
    left: 8,
    position: 'absolute',
    top: 17,
    width: 27,
  },
  woodenDesk: {
    bottom: 92,
    height: 178,
    left: 20,
    position: 'absolute',
    right: 20,
    zIndex: 4,
  },
  deskTop: {
    backgroundColor: '#8A5431',
    borderRadius: 28,
    height: 86,
    shadowColor: '#3C2416',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.28,
    shadowRadius: 20,
  },
  deskFront: {
    backgroundColor: '#6F4026',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    height: 94,
    marginHorizontal: 20,
    marginTop: -8,
  },
  deskDrawer: {
    backgroundColor: 'rgba(255, 209, 102, 0.09)',
    borderColor: 'rgba(255, 226, 169, 0.16)',
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    left: 82,
    position: 'absolute',
    right: 82,
    top: 22,
  },
  deskKnob: {
    backgroundColor: '#FFD166',
    borderRadius: 5,
    height: 10,
    left: '50%',
    marginLeft: -5,
    position: 'absolute',
    top: 39,
    width: 10,
  },
  storybookPressable: {
    bottom: 26,
    left: 30,
    position: 'absolute',
    zIndex: 3,
  },
  storybookAnimatedSurface: {
    transform: [{ rotate: '-8deg' }],
  },
  storybookCover: {
    borderColor: 'rgba(255,255,255,0.38)',
    borderRadius: 18,
    borderWidth: 1,
    height: 122,
    overflow: 'hidden',
    padding: 14,
    shadowColor: '#3C2416',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    width: 138,
  },
  storybookGlow: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 48,
    height: 96,
    position: 'absolute',
    right: -28,
    top: -24,
    width: 96,
  },
  storybookEyebrow: {
    color: '#5A321A',
    fontSize: 11,
    fontWeight: '900',
  },
  storybookTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
    marginTop: 8,
  },
  storybookLine: {
    backgroundColor: 'rgba(255,255,255,0.58)',
    borderRadius: 2,
    height: 3,
    marginTop: 11,
    width: 68,
  },
  storybookHint: {
    color: '#FFF7D8',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 8,
  },
  deskLamp: {
    position: 'absolute',
    right: 34,
    top: -54,
  },
  lampShade: {
    backgroundColor: '#FFE7A3',
    borderRadius: 22,
    height: 42,
    shadowColor: '#FFD166',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 22,
    width: 76,
  },
  lampStem: {
    backgroundColor: '#5B3520',
    height: 48,
    marginLeft: 34,
    width: 8,
  },
  lampBase: {
    backgroundColor: '#5B3520',
    borderRadius: 18,
    height: 18,
    marginLeft: 18,
    width: 44,
  },
  bedroomFloor: {
    backgroundColor: '#6F462E',
    bottom: 0,
    height: '30%',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  detailContent: {
    paddingBottom: 116,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  detailTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  detailRoundButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.09)',
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 17,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  favoriteButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.09)',
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 17,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  detailHero: {
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 28,
    borderWidth: 1,
    height: 330,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
  },
  detailHeroImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  detailHeroGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '72%',
  },
  detailHeroCopy: {
    bottom: 24,
    left: 22,
    position: 'absolute',
    width: 260,
  },
  detailBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 235, 160, 0.96)',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 7,
    marginBottom: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  detailBadgeText: {
    color: '#101827',
    fontSize: 12,
    fontWeight: '900',
  },
  detailTitle: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 38,
  },
  detailMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginTop: 12,
  },
  detailSection: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 16,
    padding: 18,
  },
  detailSectionTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 12,
  },
  detailBodyText: {
    color: '#C9D1E2',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
    marginTop: 7,
  },
  actionGrid: {
    gap: 10,
    marginTop: 16,
  },
  actionButton: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 62,
    paddingHorizontal: 16,
  },
  actionButtonHighlighted: {
    borderColor: 'rgba(255, 209, 102, 0.62)',
  },
  actionButtonText: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
  },
  actionButtonTextHighlighted: {
    color: '#101827',
  },
  earnGrid: {
    gap: 10,
  },
  earnItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 17,
    flexDirection: 'row',
    gap: 12,
    padding: 13,
  },
  earnIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 209, 102, 0.14)',
    borderRadius: 14,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  earnLabel: {
    color: '#AEBBD0',
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
  },
  earnValue: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  recommendationRow: {
    gap: 12,
    paddingRight: 12,
  },
  recommendedCard: {
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 20,
    borderWidth: 1,
    height: 150,
    overflow: 'hidden',
    width: 150,
  },
  recommendedImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  recommendedFade: {
    bottom: 0,
    height: 90,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  recommendedTitle: {
    bottom: 13,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    left: 13,
    lineHeight: 18,
    position: 'absolute',
    right: 13,
  },
  journeyContent: {
    paddingBottom: 38,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  journeyStepPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.09)',
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  journeyStepText: {
    color: '#D9E2F2',
    fontSize: 12,
    fontWeight: '900',
  },
  journeyHero: {
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 28,
    borderWidth: 1,
    height: 310,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
  },
  journeyHeroImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  journeyHeroGradient: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '78%',
  },
  journeyHeroCopy: {
    bottom: 24,
    left: 22,
    position: 'absolute',
    width: 270,
  },
  journeyTitle: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '900',
    lineHeight: 36,
  },
  journeyDescription: {
    color: '#DDE6F6',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
    marginTop: 10,
  },
  journeyPanel: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 16,
    padding: 18,
  },
  journeyPanelTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 12,
  },
  journeyBodyText: {
    color: '#C9D1E2',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 23,
  },
  journeyListItem: {
    alignItems: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 17,
    flexDirection: 'row',
    gap: 12,
    marginTop: 10,
    padding: 13,
  },
  journeyListIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 209, 102, 0.14)',
    borderRadius: 14,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  journeyListCopy: {
    flex: 1,
  },
  journeyListTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  journeyListBody: {
    color: '#C9D1E2',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    marginTop: 4,
  },
  cloudBubble: {
    backgroundColor: 'rgba(255, 209, 102, 0.12)',
    borderColor: 'rgba(255, 209, 102, 0.28)',
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
  },
  cloudBubbleText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 23,
  },
  journeyPrimaryButton: {
    alignItems: 'center',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 58,
    paddingHorizontal: 18,
  },
  journeyPrimaryText: {
    color: '#101827',
    fontSize: 17,
    fontWeight: '900',
  },
  questionContent: {
    paddingBottom: 38,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  questionHero: {
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 30,
    borderWidth: 1,
    height: 350,
    overflow: 'hidden',
    shadowColor: '#FFB347',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.24,
    shadowRadius: 24,
  },
  questionHeroImage: {
    bottom: 0,
    height: '100%',
    position: 'absolute',
    right: 0,
    width: '100%',
  },
  questionHeroFade: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '82%',
  },
  questionHeroCopy: {
    bottom: 26,
    left: 22,
    position: 'absolute',
    width: 276,
  },
  questionCloudLine: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 35,
  },
  questionPanel: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 16,
    padding: 18,
  },
  questionTitle: {
    color: '#FFFFFF',
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 31,
  },
  answerStack: {
    gap: 12,
    marginTop: 18,
  },
  answerCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 13,
    minHeight: 76,
    paddingHorizontal: 16,
  },
  answerCardSelected: {
    backgroundColor: 'rgba(255, 209, 102, 0.13)',
    borderColor: 'rgba(255, 209, 102, 0.55)',
  },
  answerIcon: {
    fontSize: 28,
  },
  answerText: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 17,
    fontWeight: '900',
    lineHeight: 22,
  },
  questionResponsePanel: {
    marginTop: 16,
  },
  storyScreen: {
    flex: 1,
  },
  storyPage: {
    flex: 1,
    overflow: 'hidden',
  },
  storyIllustration: {
    height: '72%',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  storyImageFade: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  storyTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 24,
    position: 'absolute',
    right: 24,
    top: 20,
    zIndex: 3,
  },
  storyCopyPanel: {
    bottom: 24,
    left: 24,
    position: 'absolute',
    right: 24,
    zIndex: 2,
  },
  storyTitle: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 38,
  },
  storyParagraphStack: {
    gap: 8,
    marginTop: 13,
  },
  storyParagraph: {
    color: '#DDE6F6',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 23,
  },
  storyContinueButton: {
    alignItems: 'center',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 20,
    minHeight: 58,
    paddingHorizontal: 18,
  },
  storyContinueText: {
    color: '#101827',
    fontSize: 17,
    fontWeight: '900',
  },
  storyChoiceGrid: {
    gap: 12,
    marginTop: 18,
  },
  storyChoiceCard: {
    borderRadius: 22,
    height: 138,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
  },
  storyChoiceGradient: {
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    overflow: 'hidden',
  },
  storyChoiceImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '56%',
  },
  storyChoiceFade: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  storyChoiceCopy: {
    bottom: 16,
    left: 16,
    position: 'absolute',
    right: 104,
  },
  storyChoiceTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 23,
  },
  storyChoiceBody: {
    color: '#EAF0FA',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
    marginTop: 7,
  },
  congratsHero: {
    borderColor: 'rgba(255, 209, 102, 0.5)',
    borderRadius: 30,
    borderWidth: 1,
    height: 410,
    marginTop: 8,
    overflow: 'hidden',
    shadowColor: '#FFB347',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.26,
    shadowRadius: 26,
  },
  congratsHeroImage: {
    height: '100%',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  congratsFade: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '84%',
  },
  congratsCopy: {
    bottom: 28,
    left: 24,
    position: 'absolute',
    right: 24,
  },
  congratsIcon: {
    alignItems: 'center',
    backgroundColor: '#FFD166',
    borderRadius: 21,
    height: 48,
    justifyContent: 'center',
    marginBottom: 16,
    width: 48,
  },
  congratsTitle: {
    color: '#FFFFFF',
    fontSize: 36,
    fontWeight: '900',
    lineHeight: 40,
  },
  congratsBody: {
    color: '#DDE6F6',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 23,
    marginTop: 10,
  },
  bottomNav: {
    alignItems: 'center',
    backgroundColor: 'rgba(8, 15, 31, 0.96)',
    borderColor: 'rgba(148, 120, 255, 0.36)',
    borderRadius: 24,
    borderWidth: 1,
    bottom: 15,
    flexDirection: 'row',
    height: 66,
    justifyContent: 'space-around',
    left: 24,
    position: 'absolute',
    right: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.36,
    shadowRadius: 18,
    elevation: 10,
  },
  navItem: {
    alignItems: 'center',
    gap: 4,
    justifyContent: 'center',
    width: 60,
  },
  navLabel: {
    color: '#9AA6BC',
    fontSize: 10,
    fontWeight: '800',
  },
  navLabelActive: {
    color: '#FFD166',
  },
});
