import { Category, WisdomWorld } from '../types/wisdom';

export const assets = {
  hero: require('../../assets/cloud/cloud-full-body.png'),
  next: require('../../assets/cloud/cloud-thinking.png'),
  threeJars: require('../../assets/cloud/cloud-reading.png'),
  piggy: require('../../assets/cloud/cat-money.png'),
  completed: require('../../assets/cloud/cloud-helps-friend.png'),
  investing: require('../../assets/cloud/cloud-thinking.png'),
  avatar: require('../../assets/cloud/cloud-avatar.png'),
  money: require('../../assets/cloud/cat-money.png'),
  street: require('../../assets/cloud/cat-street.png'),
  people: require('../../assets/cloud/cat-people.png'),
  thinking: require('../../assets/cloud/cat-thinking.png'),
  communication: require('../../assets/cloud/cat-communication.png'),
  modern: require('../../assets/cloud/cat-modern.png'),
};

export const globalIdentity = {
  current: 'Young Investor',
  completed: '12 total wisdoms completed',
  next: 'Money Builder',
};

export const categories: Category[] = [
  { key: 'money', label: 'Money', icon: 'cash-outline', colors: ['#66BB39', '#12763F'], image: assets.money },
  { key: 'street', label: 'Street', icon: 'shield-checkmark-outline', colors: ['#3BA3FF', '#224B9C'], image: assets.street },
  { key: 'people', label: 'People', icon: 'heart', colors: ['#FB5FA5', '#9D2D74'], image: assets.people },
  { key: 'thinking', label: 'Thinking', icon: 'bulb', colors: ['#7A5CFF', '#3D2BA3'], image: assets.thinking },
  { key: 'comm', label: 'Comm.', icon: 'chatbubble-ellipses', colors: ['#2DD4D4', '#0D7186'], image: assets.communication },
  { key: 'modern', label: 'Modern', icon: 'globe-outline', colors: ['#2E9CF2', '#154C95'], image: assets.modern },
];

export const worlds: WisdomWorld[] = [
  {
    ...categories[0],
    background: ['#081326', '#0B1E24'],
    heroTitle: 'Needs vs\nWants',
    heroDescription: 'Learn how to choose what truly matters before spending your resources.',
    heroMinutes: 8,
    heroImage: assets.hero,
    heroColors: ['#F7B733', '#E88A1A'],
    lockedTitle: 'Three Jars Method',
    lockedDescription: 'Cloud is preparing this for tomorrow.',
    lockedMinutes: 7,
    lockedImage: assets.threeJars,
    lockedColors: ['#39235E', '#171C4C'],
  },
  {
    ...categories[1],
    background: ['#071326', '#0F2F57'],
    heroTitle: 'Trust Your\nInstincts',
    heroDescription: 'Notice what feels wrong, pause, and choose the safer next step.',
    heroMinutes: 7,
    heroImage: assets.street,
    heroColors: ['#2257B8', '#1B2E72'],
    lockedTitle: 'Reading People',
    lockedDescription: 'Cloud is preparing this for tomorrow.',
    lockedMinutes: 8,
    lockedImage: assets.street,
    lockedColors: ['#263B76', '#171C4C'],
  },
  {
    ...categories[2],
    background: ['#170B22', '#3E1739'],
    heroTitle: 'Kind\nBoundaries',
    heroDescription: 'Learn how to be warm and still say no when something is not right.',
    heroMinutes: 8,
    heroImage: assets.people,
    heroColors: ['#FB5FA5', '#8F2E65'],
    lockedTitle: 'Reading Feelings',
    lockedDescription: 'Cloud is preparing this for tomorrow.',
    lockedMinutes: 7,
    lockedImage: assets.people,
    lockedColors: ['#64304C', '#251B3F'],
  },
  {
    ...categories[3],
    background: ['#100F2B', '#2C1E5F'],
    heroTitle: 'Pause Before\nReacting',
    heroDescription: 'Give your wiser self one breath to arrive before you choose.',
    heroMinutes: 5,
    heroImage: assets.thinking,
    heroColors: ['#7A5CFF', '#3D2BA3'],
    lockedTitle: 'Puzzle Thinking',
    lockedDescription: 'Cloud is preparing this for tomorrow.',
    lockedMinutes: 6,
    lockedImage: assets.thinking,
    lockedColors: ['#4A347D', '#191B4C'],
  },
  {
    ...categories[4],
    background: ['#071A24', '#0C3F4B'],
    heroTitle: 'Use Clear\nWords',
    heroDescription: 'Say what you mean with courage, kindness, and simple words.',
    heroMinutes: 6,
    heroImage: assets.communication,
    heroColors: ['#2DD4D4', '#0D7186'],
    lockedTitle: 'Ask Better Questions',
    lockedDescription: 'Cloud is preparing this for tomorrow.',
    lockedMinutes: 8,
    lockedImage: assets.communication,
    lockedColors: ['#1E5B72', '#122A45'],
  },
  {
    ...categories[5],
    background: ['#071326', '#0D3564'],
    heroTitle: 'Digital\nFootprints',
    heroDescription: 'Learn why online choices can travel farther than you expect.',
    heroMinutes: 9,
    heroImage: assets.modern,
    heroColors: ['#2E9CF2', '#154C95'],
    lockedTitle: 'Online Safety',
    lockedDescription: 'Cloud is preparing this for tomorrow.',
    lockedMinutes: 7,
    lockedImage: assets.modern,
    lockedColors: ['#174B82', '#14214A'],
  },
];

export const recommendedWisdoms = [
  { title: 'Three Jars Method', image: assets.threeJars, colors: ['#39235E', '#171C4C'] as [string, string] },
  { title: 'Save Before You Spend', image: assets.piggy, colors: ['#14532D', '#073B3A'] as [string, string] },
  { title: 'Opportunity Cost', image: assets.completed, colors: ['#1E2E86', '#071C4A'] as [string, string] },
];
