import {
  Category,
  Challenge,
  Conversation,
  GlobalIdentity,
  RecommendedWisdomCard,
  Reward,
  Story,
  Wisdom,
} from '../types/wisdom';

export const assets = {
  hero: require('../../assets/cloud/cloud-full-body.png'),
  next: require('../../assets/cloud/cloud-thinking.png'),
  threeJars: require('../../assets/cloud/cloud-reading.png'),
  piggy: require('../../assets/cloud/cat-money.png'),
  completed: require('../../assets/cloud/cloud-helps-friend.png'),
  investing: require('../../assets/cloud/cloud-thinking.png'),
  avatar: require('../../assets/cloud/cloud-avatar.png'),
  money: require('../../assets/cloud/cat-money.png'),
  street: require('../../assets/cloud/cat-street.png'),
  people: require('../../assets/cloud/cat-people.png'),
  thinking: require('../../assets/cloud/cat-thinking.png'),
  communication: require('../../assets/cloud/cat-communication.png'),
  modern: require('../../assets/cloud/cat-modern.png'),
  bedroomScene: require('../../assets/cloud/home-bedroom-scene.png'),
  lockedStorybook: require('../../assets/cloud/locked-storybook.png'),
  needsWantsJars: require('../../assets/cloud/needs-wants-jars.png'),
};

export const globalIdentity: GlobalIdentity = {
  current: 'Young Investor',
  completed: '12 wise moments practiced',
  next: 'Money Builder',
};

export const categories: Category[] = [
  {
    id: 'money',
    title: 'Money Wisdom',
    shortTitle: 'Money',
    icon: 'cash-outline',
    color: ['#66BB39', '#12763F'],
    description: 'Practice thoughtful choices with saving, spending, giving, and growing money.',
    image: assets.money,
    background: ['#081326', '#0B1E24'],
    heroColors: ['#F7B733', '#E88A1A'],
    lockedColors: ['#39235E', '#171C4C'],
  },
  {
    id: 'street',
    title: 'Street Wisdom',
    shortTitle: 'Street',
    icon: 'shield-checkmark-outline',
    color: ['#3BA3FF', '#224B9C'],
    description: 'Notice the world, trust signals, and choose safer next steps.',
    image: assets.street,
    background: ['#071326', '#0F2F57'],
    heroColors: ['#2257B8', '#1B2E72'],
    lockedColors: ['#263B76', '#171C4C'],
  },
  {
    id: 'people',
    title: 'People Wisdom',
    shortTitle: 'People',
    icon: 'heart',
    color: ['#FB5FA5', '#9D2D74'],
    description: 'Become kind, confident, and steady with friends, family, and new people.',
    image: assets.people,
    background: ['#170B22', '#3E1739'],
    heroColors: ['#FB5FA5', '#8F2E65'],
    lockedColors: ['#64304C', '#251B3F'],
  },
  {
    id: 'thinking',
    title: 'Thinking Wisdom',
    shortTitle: 'Thinking',
    icon: 'bulb',
    color: ['#7A5CFF', '#3D2BA3'],
    description: 'Build calm thinking, better questions, and wiser reactions.',
    image: assets.thinking,
    background: ['#100F2B', '#2C1E5F'],
    heroColors: ['#7A5CFF', '#3D2BA3'],
    lockedColors: ['#4A347D', '#191B4C'],
  },
  {
    id: 'comm',
    title: 'Communication Wisdom',
    shortTitle: 'Comm.',
    icon: 'chatbubble-ellipses',
    color: ['#2DD4D4', '#0D7186'],
    description: 'Say true things with courage, kindness, and clear words.',
    image: assets.communication,
    background: ['#071A24', '#0C3F4B'],
    heroColors: ['#2DD4D4', '#0D7186'],
    lockedColors: ['#1E5B72', '#122A45'],
  },
  {
    id: 'modern',
    title: 'Modern World Wisdom',
    shortTitle: 'Modern',
    icon: 'globe-outline',
    color: ['#2E9CF2', '#154C95'],
    description: 'Grow up thoughtful, safe, and confident in a digital world.',
    image: assets.modern,
    background: ['#071326', '#0D3564'],
    heroColors: ['#2E9CF2', '#154C95'],
    lockedColors: ['#174B82', '#14214A'],
  },
];

export const wisdoms: Wisdom[] = [
  {
    id: 'needs-vs-wants',
    categoryId: 'money',
    title: 'Needs vs Wants',
    displayTitle: 'Needs vs\nWants',
    subtitle: 'Practice becoming someone who chooses what truly matters before spending.',
    coverImage: assets.hero,
    estimatedMinutes: 8,
    difficulty: 'beginner',
    becomingTitle: 'Wiser at Needs vs Wants',
    nextIdentity: 'Money Builder',
    storyId: 'story-needs-vs-wants',
    challengeId: 'challenge-needs-vs-wants',
    conversationId: 'conversation-needs-vs-wants',
    rewardId: 'reward-needs-vs-wants',
    order: 1,
    isPremium: false,
    tags: ['money', 'choices', 'saving', 'needs', 'wants'],
    status: 'available',
    locale: 'en-US',
  },
  {
    id: 'three-jars-method',
    categoryId: 'money',
    title: 'Three Jars Method',
    displayTitle: 'Three Jars Method',
    subtitle: 'Cloud is preparing your next step for tomorrow.',
    coverImage: assets.threeJars,
    estimatedMinutes: 7,
    difficulty: 'beginner',
    becomingTitle: 'Thoughtful Money Keeper',
    nextIdentity: 'Money Builder',
    storyId: 'story-three-jars-method',
    challengeId: 'challenge-three-jars-method',
    conversationId: 'conversation-three-jars-method',
    rewardId: 'reward-three-jars-method',
    order: 2,
    isPremium: false,
    tags: ['money', 'saving', 'giving', 'spending'],
    status: 'locked',
    locale: 'en-US',
  },
  {
    id: 'save-before-you-spend',
    categoryId: 'money',
    title: 'Save Before You Spend',
    displayTitle: 'Save Before\nYou Spend',
    subtitle: 'Let future you have a choice too.',
    coverImage: assets.piggy,
    estimatedMinutes: 6,
    difficulty: 'beginner',
    becomingTitle: 'Patient Saver',
    nextIdentity: 'Money Builder',
    storyId: 'story-save-before-you-spend',
    challengeId: 'challenge-save-before-you-spend',
    conversationId: 'conversation-save-before-you-spend',
    rewardId: 'reward-save-before-you-spend',
    order: 3,
    isPremium: false,
    tags: ['money', 'saving', 'patience'],
    status: 'completed',
    locale: 'en-US',
  },
  {
    id: 'opportunity-cost',
    categoryId: 'money',
    title: 'Opportunity Cost',
    displayTitle: 'Opportunity\nCost',
    subtitle: 'Every yes quietly says no to something else.',
    coverImage: assets.completed,
    estimatedMinutes: 7,
    difficulty: 'growing',
    becomingTitle: 'Careful Chooser',
    nextIdentity: 'Money Builder',
    storyId: 'story-opportunity-cost',
    challengeId: 'challenge-opportunity-cost',
    conversationId: 'conversation-opportunity-cost',
    rewardId: 'reward-opportunity-cost',
    order: 4,
    isPremium: false,
    tags: ['money', 'tradeoffs', 'choices'],
    status: 'completed',
    locale: 'en-US',
  },
  {
    id: 'trust-your-instincts',
    categoryId: 'street',
    title: 'Trust Your Instincts',
    displayTitle: 'Trust Your\nInstincts',
    subtitle: 'Become someone who notices, pauses, and chooses the safer next step.',
    coverImage: assets.street,
    estimatedMinutes: 7,
    difficulty: 'beginner',
    becomingTitle: 'Safe Explorer',
    nextIdentity: 'Wise Navigator',
    storyId: 'story-trust-your-instincts',
    challengeId: 'challenge-trust-your-instincts',
    conversationId: 'conversation-trust-your-instincts',
    rewardId: 'reward-trust-your-instincts',
    order: 1,
    isPremium: false,
    tags: ['safety', 'awareness', 'street'],
    status: 'available',
    locale: 'en-US',
  },
  {
    id: 'reading-people',
    categoryId: 'street',
    title: 'Reading People',
    displayTitle: 'Reading People',
    subtitle: 'Cloud is preparing your next step for tomorrow.',
    coverImage: assets.street,
    estimatedMinutes: 8,
    difficulty: 'growing',
    becomingTitle: 'Careful Observer',
    nextIdentity: 'Wise Navigator',
    storyId: 'story-reading-people',
    challengeId: 'challenge-reading-people',
    conversationId: 'conversation-reading-people',
    rewardId: 'reward-reading-people',
    order: 2,
    isPremium: false,
    tags: ['safety', 'people', 'awareness'],
    status: 'locked',
    locale: 'en-US',
  },
  {
    id: 'kind-boundaries',
    categoryId: 'people',
    title: 'Kind Boundaries',
    displayTitle: 'Kind\nBoundaries',
    subtitle: 'Become warm enough to care and strong enough to say no.',
    coverImage: assets.people,
    estimatedMinutes: 8,
    difficulty: 'beginner',
    becomingTitle: 'Kind Boundary Keeper',
    nextIdentity: 'Confident Friend',
    storyId: 'story-kind-boundaries',
    challengeId: 'challenge-kind-boundaries',
    conversationId: 'conversation-kind-boundaries',
    rewardId: 'reward-kind-boundaries',
    order: 1,
    isPremium: false,
    tags: ['people', 'boundaries', 'kindness'],
    status: 'available',
    locale: 'en-US',
  },
  {
    id: 'reading-feelings',
    categoryId: 'people',
    title: 'Reading Feelings',
    displayTitle: 'Reading Feelings',
    subtitle: 'Cloud is preparing your next step for tomorrow.',
    coverImage: assets.people,
    estimatedMinutes: 7,
    difficulty: 'beginner',
    becomingTitle: 'Thoughtful Friend',
    nextIdentity: 'Confident Friend',
    storyId: 'story-reading-feelings',
    challengeId: 'challenge-reading-feelings',
    conversationId: 'conversation-reading-feelings',
    rewardId: 'reward-reading-feelings',
    order: 2,
    isPremium: false,
    tags: ['people', 'feelings', 'empathy'],
    status: 'locked',
    locale: 'en-US',
  },
  {
    id: 'pause-before-reacting',
    categoryId: 'thinking',
    title: 'Pause Before Reacting',
    displayTitle: 'Pause Before\nReacting',
    subtitle: 'Give your wiser self one breath to arrive before you choose.',
    coverImage: assets.thinking,
    estimatedMinutes: 5,
    difficulty: 'beginner',
    becomingTitle: 'Calm Thinker',
    nextIdentity: 'Thoughtful Thinker',
    storyId: 'story-pause-before-reacting',
    challengeId: 'challenge-pause-before-reacting',
    conversationId: 'conversation-pause-before-reacting',
    rewardId: 'reward-pause-before-reacting',
    order: 1,
    isPremium: false,
    tags: ['thinking', 'calm', 'emotions'],
    status: 'available',
    locale: 'en-US',
  },
  {
    id: 'puzzle-thinking',
    categoryId: 'thinking',
    title: 'Puzzle Thinking',
    displayTitle: 'Puzzle Thinking',
    subtitle: 'Cloud is preparing your next step for tomorrow.',
    coverImage: assets.thinking,
    estimatedMinutes: 6,
    difficulty: 'beginner',
    becomingTitle: 'Question Builder',
    nextIdentity: 'Thoughtful Thinker',
    storyId: 'story-puzzle-thinking',
    challengeId: 'challenge-puzzle-thinking',
    conversationId: 'conversation-puzzle-thinking',
    rewardId: 'reward-puzzle-thinking',
    order: 2,
    isPremium: false,
    tags: ['thinking', 'questions', 'problem-solving'],
    status: 'locked',
    locale: 'en-US',
  },
  {
    id: 'use-clear-words',
    categoryId: 'comm',
    title: 'Use Clear Words',
    displayTitle: 'Use Clear\nWords',
    subtitle: 'Say what you mean with courage, kindness, and simple words.',
    coverImage: assets.communication,
    estimatedMinutes: 6,
    difficulty: 'beginner',
    becomingTitle: 'Clear Speaker',
    nextIdentity: 'Confident Speaker',
    storyId: 'story-use-clear-words',
    challengeId: 'challenge-use-clear-words',
    conversationId: 'conversation-use-clear-words',
    rewardId: 'reward-use-clear-words',
    order: 1,
    isPremium: false,
    tags: ['communication', 'clarity', 'courage'],
    status: 'available',
    locale: 'en-US',
  },
  {
    id: 'ask-better-questions',
    categoryId: 'comm',
    title: 'Ask Better Questions',
    displayTitle: 'Ask Better Questions',
    subtitle: 'Cloud is preparing your next step for tomorrow.',
    coverImage: assets.communication,
    estimatedMinutes: 8,
    difficulty: 'growing',
    becomingTitle: 'Curious Communicator',
    nextIdentity: 'Confident Speaker',
    storyId: 'story-ask-better-questions',
    challengeId: 'challenge-ask-better-questions',
    conversationId: 'conversation-ask-better-questions',
    rewardId: 'reward-ask-better-questions',
    order: 2,
    isPremium: false,
    tags: ['communication', 'questions', 'listening'],
    status: 'locked',
    locale: 'en-US',
  },
  {
    id: 'digital-footprints',
    categoryId: 'modern',
    title: 'Digital Footprints',
    displayTitle: 'Digital\nFootprints',
    subtitle: 'Become someone who thinks before sharing in the modern world.',
    coverImage: assets.modern,
    estimatedMinutes: 9,
    difficulty: 'beginner',
    becomingTitle: 'Careful Digital Citizen',
    nextIdentity: 'Modern World Navigator',
    storyId: 'story-digital-footprints',
    challengeId: 'challenge-digital-footprints',
    conversationId: 'conversation-digital-footprints',
    rewardId: 'reward-digital-footprints',
    order: 1,
    isPremium: false,
    tags: ['modern', 'digital', 'safety'],
    status: 'available',
    locale: 'en-US',
  },
  {
    id: 'online-safety',
    categoryId: 'modern',
    title: 'Online Safety',
    displayTitle: 'Online Safety',
    subtitle: 'Cloud is preparing your next step for tomorrow.',
    coverImage: assets.modern,
    estimatedMinutes: 7,
    difficulty: 'beginner',
    becomingTitle: 'Safe Digital Explorer',
    nextIdentity: 'Modern World Navigator',
    storyId: 'story-online-safety',
    challengeId: 'challenge-online-safety',
    conversationId: 'conversation-online-safety',
    rewardId: 'reward-online-safety',
    order: 2,
    isPremium: false,
    tags: ['modern', 'safety', 'privacy'],
    status: 'locked',
    locale: 'en-US',
  },
];

export const stories: Story[] = [
  {
    id: 'story-needs-vs-wants',
    wisdomId: 'needs-vs-wants',
    pages: [
      {
        id: 'cover',
        wisdomId: 'needs-vs-wants',
        eyebrow: 'Needs vs Wants',
        title: 'The Twenty Dollar Question',
        body: [
          'Cloud found a crisp twenty dollar bill on the kitchen table.',
          'Beside it were two glass jars. One said Needs. One said Wants.',
        ],
        image: assets.hero,
        emotion: 'curious',
        interactionType: 'tap',
      },
      {
        id: 'cloud-pause',
        wisdomId: 'needs-vs-wants',
        eyebrow: 'Cloud whispers',
        title: 'Before we spend, we pause.',
        body: ['Some choices sparkle right away.', 'Some choices quietly help future you.'],
        image: assets.next,
        emotion: 'thoughtful',
        interactionType: 'tap',
      },
      {
        id: 'story-room',
        wisdomId: 'needs-vs-wants',
        eyebrow: 'Story moment',
        title: 'A tiny choice can show who you are becoming.',
        body: ['Cloud looked at the money, then at the jars.', 'He wondered which choice would make him feel proud tomorrow.'],
        image: assets.threeJars,
        emotion: 'curious',
        interactionType: 'tap',
      },
      {
        id: 'choice',
        wisdomId: 'needs-vs-wants',
        eyebrow: 'Your turn',
        title: 'If your parents gave you $20 today, what would you do?',
        body: ['Choose the path Cloud should explore first.'],
        image: assets.piggy,
        emotion: 'curious',
        interactionType: 'choice',
        choiceOptions: [
          {
            id: 'fun-now',
            title: 'Buy something fun now',
            body: 'A treat, a drink, or a small toy today.',
            image: assets.piggy,
            colors: ['rgba(255, 179, 71, 0.95)', 'rgba(180, 83, 9, 0.82)'],
            branchId: 'fun-now',
          },
          {
            id: 'save-bigger',
            title: 'Save it for something bigger',
            body: 'Let the money wait for a dream that matters.',
            image: assets.threeJars,
            colors: ['rgba(34, 197, 94, 0.92)', 'rgba(20, 83, 45, 0.82)'],
            branchId: 'save-bigger',
          },
        ],
      },
      {
        id: 'fun-now-1',
        wisdomId: 'needs-vs-wants',
        branchId: 'fun-now',
        eyebrow: 'Path chosen',
        title: 'The fun thing felt exciting.',
        body: ['Cloud bought something bright and sweet.', 'For a little while, it felt like the best choice in the world.'],
        image: assets.piggy,
        emotion: 'happy',
        interactionType: 'tap',
      },
      {
        id: 'fun-now-2',
        wisdomId: 'needs-vs-wants',
        branchId: 'fun-now',
        eyebrow: 'Cloud notices',
        title: 'Then the moment passed.',
        body: ['The treat was gone, and the twenty dollars was gone too.', 'Cloud did not feel bad. He felt curious.'],
        image: assets.next,
        emotion: 'thoughtful',
        interactionType: 'tap',
      },
      {
        id: 'save-bigger-1',
        wisdomId: 'needs-vs-wants',
        branchId: 'save-bigger',
        eyebrow: 'Path chosen',
        title: 'The money waited in the jar.',
        body: ['Cloud placed the bill carefully into the Wants jar.', 'It was not as exciting as spending it, but it felt steady.'],
        image: assets.threeJars,
        emotion: 'calm',
        interactionType: 'tap',
      },
      {
        id: 'save-bigger-2',
        wisdomId: 'needs-vs-wants',
        branchId: 'save-bigger',
        eyebrow: 'Cloud notices',
        title: 'A bigger dream came into view.',
        body: ['The next day, Cloud remembered something he wanted even more.', 'Waiting had given future Cloud a choice too.'],
        image: assets.investing,
        emotion: 'proud',
        interactionType: 'tap',
      },
      {
        id: 'reflection',
        wisdomId: 'needs-vs-wants',
        eyebrow: 'Cloud reflects',
        title: 'A want is not bad.',
        body: ['Wants can bring joy. Needs help you live and grow.', 'Wisdom is learning which one should come first.'],
        image: assets.next,
        emotion: 'thoughtful',
        interactionType: 'reflection',
        buttonLabel: "See today's challenge",
      },
      {
        id: 'challenge',
        wisdomId: 'needs-vs-wants',
        eyebrow: "Today's Challenge",
        title: 'Find one Need and one Want.',
        body: [
          'Look around your real life today.',
          'Name one thing that helps you grow, and one fun thing that can wait its turn.',
        ],
        image: assets.completed,
        emotion: 'proud',
        interactionType: 'challenge',
        buttonLabel: 'See who I am becoming',
      },
      {
        id: 'becoming',
        wisdomId: 'needs-vs-wants',
        eyebrow: 'Becoming',
        title: globalIdentity.current,
        body: [
          'Today you practiced Needs vs Wants.',
          `You are growing toward ${globalIdentity.next}, one thoughtful choice at a time.`,
        ],
        image: assets.hero,
        emotion: 'proud',
        interactionType: 'becoming',
        buttonLabel: 'Talk with Cloud',
      },
    ],
  },
];

const placeholderSteps = [
  {
    id: 'notice',
    title: 'Notice the moment',
    body: 'Pause and name what is happening before choosing.',
    icon: 'eye-outline' as const,
  },
  {
    id: 'choose',
    title: 'Choose your wiser step',
    body: 'Pick one small action that helps the person you are becoming.',
    icon: 'checkmark-circle-outline' as const,
  },
];

export const challenges: Challenge[] = [
  {
    id: 'challenge-needs-vs-wants',
    wisdomId: 'needs-vs-wants',
    title: 'Practice a wiser choice',
    description: 'Find one need and one want in your real life today, then choose what matters first.',
    steps: [
      {
        id: 'challenge-start',
        title: 'Practice a wiser choice',
        body: 'Find one need and one want in your real life today, then choose what matters first.',
        icon: 'flag-outline',
      },
      {
        id: 'find-need',
        title: 'Find one need',
        body: 'Think of something your family must buy or use this week.',
        icon: 'basket-outline',
      },
      {
        id: 'find-want',
        title: 'Find one want',
        body: 'Think of something fun that can wait until later.',
        icon: 'gift-outline',
      },
      {
        id: 'sort-jars',
        title: 'Put them in the right jar',
        body: 'Needs first. Wants after the important things are safe.',
        icon: 'albums-outline',
      },
    ],
  },
  ...wisdoms
    .filter((wisdom) => wisdom.id !== 'needs-vs-wants')
    .map((wisdom): Challenge => ({
      id: wisdom.challengeId,
      wisdomId: wisdom.id,
      title: `Practice ${wisdom.title}`,
      description: 'A small real-life practice Cloud is preparing for this wisdom.',
      steps: placeholderSteps,
    })),
];

export const conversations: Conversation[] = [
  {
    id: 'conversation-needs-vs-wants',
    wisdomId: 'needs-vs-wants',
    openingQuestion: 'If you had money for only one thing today, how would you decide what matters most?',
    suggestedReplies: [
      'I would ask if it helps me grow.',
      'I would think about whether future me needs it.',
      'I would talk with someone I trust first.',
    ],
  },
  ...wisdoms
    .filter((wisdom) => wisdom.id !== 'needs-vs-wants')
    .map((wisdom): Conversation => ({
      id: wisdom.conversationId,
      wisdomId: wisdom.id,
      openingQuestion: `What kind of person could ${wisdom.title} help you become?`,
      suggestedReplies: ['Someone calmer.', 'Someone kinder.', 'Someone who chooses with care.'],
    })),
];

export const rewards: Reward[] = wisdoms.map((wisdom) => ({
  id: wisdom.rewardId,
  wisdomId: wisdom.id,
  title: wisdom.becomingTitle,
  description: `You practiced becoming ${wisdom.becomingTitle.toLowerCase()}.`,
}));

export const recommendedWisdoms: RecommendedWisdomCard[] = [
  { title: 'Three Jars Method', image: assets.threeJars, colors: ['#39235E', '#171C4C'] },
  { title: 'Save Before You Spend', image: assets.piggy, colors: ['#14532D', '#073B3A'] },
  { title: 'Opportunity Cost', image: assets.completed, colors: ['#1E2E86', '#071C4A'] },
];
